const TableData = [
    {
    id: 1,
    date: '19/04/2023',
    branch: 'Thane',
    type: 'Full',
    amount: 5000,
    bank: 'Example Bank',
    requestedBy: 'ABC123',
    status: 'Approved',
  },
  {
  id: 2,
  date: '19/06/2023',
  branch: 'Navi Mumbai',
  type: 'Full',
  amount: 10000,
  bank: 'Example Bank',
  requestedBy: 'ABC123',
  status: 'Approved',
  },
  {
  id: 3,
  date: '19/04/2023',
  branch: 'Navi Mumbai',
  type: 'Full',
  amount: 10000,
  bank: 'Example Bank',
  requestedBy: 'ABC123',
  status: 'Approved',
  },
  {
  id: 4,
  date: '19/04/2023',
  branch: 'Navi Mumbai',
  type: 'Short',
  amount: 10000,
  bank: 'Example Bank',
  requestedBy: 'ABC123',
  status: 'Pending',
  },
  {
  id: 5,
  date: '19/04/2023',
  branch: 'Navi Mumbai',
  type: 'Full',
  amount: 10000,
  bank: 'Example Bank',
  requestedBy: 'ABC123',
  status: 'Approved',
  },
  {
  id: 6,
  date: '15/03/2023',
  branch: 'Navi Mumbai',
  type: 'Short',
  amount: 10000,
  bank: 'Example Bank',
  requestedBy: 'ABC123',
  status: 'Approved',
  },
  {
  id: 7,
  date: '10/02/2023',
  branch: 'Navi Mumbai',
  type: 'Full',
  amount: 10000,
  bank: 'Example Bank',
  requestedBy: 'ABC123',
  status: 'Rejected',
  },
  {
  id: 8,
  date: '01/01/2022',
  branch: 'Navi Mumbai',
  type: 'Full',
  amount: 10000,
  bank: 'Example Bank',
  requestedBy: 'ABC123',
  status: 'Pending',
  },
  ];
  
  export default TableData;